export const FETCH_COURSES = 'FETCH_COURSES';
export const ADD_NEW_COURSE_TO_STORE = 'ADD_NEW_COURSE_TO_STORE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
